import StyleDictionary from 'style-dictionary';

/* ------------------------------------------------------------------ *
 * VCP Design System — token build.
 * Tailwind v4 CSS-first theme: every token path maps onto a Tailwind
 * namespace so it becomes a real utility class.
 *
 * Utility vocabulary (matches Figma variable names):
 *   bg-surface-canvas      text-text-primary      border-stroke-default
 *   bg-action-primary-surface-default   text-accent-critical-outline-content-default
 *   text-label-lg (type ramp)           rounded-md   shadow-menu
 *
 * Spacing: VCP's px scale (2..64) equals Tailwind's default numeric
 * scale (p-1 = 4px ... p-16 = 64px), so we do NOT override spacing —
 * devs use the numbers they already know. See docs/spacing.md.
 * ------------------------------------------------------------------ */

const TW = [
  [/^color\./,   (p) => `color-${p.slice(1).join('-')}`],
  [/^(surface|text|stroke|action|accent)\./, (p) => `color-${p.join('-')}`],
  [/^radius\./,  (p) => `radius-${p.slice(1).join('-')}`],
  [/^shadow\./,  (p) => `shadow-${p.slice(1).join('-')}`],
  [/^font\.family\./, (p) => `font-${p.slice(2).join('-')}`],
  [/^font\.weight\./, (p) => `font-weight-${p.slice(2).join('-')}`],
];
const twName = (t) => {
  if (t.path[0] === 'dark') return null;              // dark handled separately
  const joined = t.path.join('.');
  for (const [re, fn] of TW) if (re.test(joined)) return fn(t.path);
  return null;
};

const val = (t) => t.$value ?? t.value;

StyleDictionary.registerFormat({
  name: 'tailwind/theme-css',
  format: ({ dictionary }) => {
    const lines = [];
    for (const t of dictionary.allTokens) {
      const name = twName(t);
      if (name) lines.push(`  --${name}: ${val(t)};${t.$description ? ` /* ${t.$description} */` : ''}`);
    }
    // type ramp -> text-* utilities with paired line-height/weight/tracking
    const WEIGHTS = { regular: 400, medium: 500, semibold: 600, bold: 700 };
    for (const t of dictionary.allTokens.filter((t) => t.path[0] === 'type')) {
      const style = t.path[1];
      const v = t.original.$value; if (!v || typeof v !== 'object') continue;
      const weight = String(v.fontWeight).replace(/\{font\.weight\.(\w+)\}/, (_, w) => WEIGHTS[w]);
      lines.push(`  --text-${style}: ${v.fontSize};`);
      lines.push(`  --text-${style}--line-height: ${typeof v.lineHeight === 'number' ? v.lineHeight : v.lineHeight};`);
      lines.push(`  --text-${style}--font-weight: ${weight};`);
      if (v.letterSpacing) lines.push(`  --text-${style}--letter-spacing: ${v.letterSpacing};`);
    }
    return [
      '/* AUTOGENERATED by Style Dictionary — do not edit. Source: tokens/ */',
      '@import "tailwindcss";', '', '@theme {', ...lines, '}', '',
      '/* Dark scheme: raw variable overrides — apply .dark on <html> or <body>. */',
      '@import "./tokens.dark.css";', '',
    ].join('\n');
  },
});

StyleDictionary.registerFormat({
  name: 'css/dark-overrides',
  format: ({ dictionary }) => {
    const lines = dictionary.allTokens
      .filter((t) => t.path[0] === 'dark')
      .map((t) => `  --color-${t.path.slice(1).join('-')}: ${val(t)};`);
    return ['/* AUTOGENERATED — VCP dark theme overrides. */', '.dark {', ...lines, '}', ''].join('\n');
  },
});

StyleDictionary.registerFormat({
  name: 'ts/tokens',
  format: ({ dictionary }) => {
    const obj = {};
    for (const t of dictionary.allTokens) {
      let cur = obj;
      t.path.forEach((seg, i) => {
        if (i === t.path.length - 1) cur[seg] = val(t);
        else cur = (cur[seg] ??= {});
      });
    }
    return `// AUTOGENERATED by Style Dictionary — do not edit. Source: tokens/\nexport const tokens = ${JSON.stringify(obj, null, 2)} as const;\nexport type Tokens = typeof tokens;\n`;
  },
});

export default {
  source: ['tokens/**/*.json'],
  platforms: {
    tailwind: {
      transformGroup: 'css',
      buildPath: 'dist/',
      files: [
        { destination: 'theme.css', format: 'tailwind/theme-css' },
        { destination: 'tokens.dark.css', format: 'css/dark-overrides' },
      ],
    },
    css: {
      transformGroup: 'css', buildPath: 'dist/',
      files: [{ destination: 'tokens.css', format: 'css/variables', options: { outputReferences: true } }],
    },
    ts: {
      transformGroup: 'js', buildPath: 'dist/',
      files: [{ destination: 'tokens.ts', format: 'ts/tokens' }],
    },
    json: {
      transformGroup: 'js', buildPath: 'dist/',
      files: [
        { destination: 'tokens.flat.json', format: 'json/flat' },
        { destination: 'tokens.json', format: 'json/nested' },
      ],
    },
  },
};
