import * as React from 'react';

export type IconName =
  | 'adjustments-horizontal'
  | 'archive-box'
  | 'arrow-down-tray'
  | 'arrow-left'
  | 'arrow-path'
  | 'arrow-right'
  | 'arrow-top-right-on-square'
  | 'arrow-up-tray'
  | 'arrow-uturn-left'
  | 'arrows-pointing-out'
  | 'arrows-up-down'
  | 'bars-3'
  | 'bell'
  | 'bell-slash'
  | 'bookmark'
  | 'briefcase'
  | 'building-office'
  | 'calendar'
  | 'chart-bar'
  | 'chat-bubble-left-right'
  | 'check'
  | 'check-circle'
  | 'chevron-down'
  | 'chevron-left'
  | 'chevron-right'
  | 'chevron-up'
  | 'clipboard'
  | 'clipboard-document-list'
  | 'clock'
  | 'cloud-arrow-up'
  | 'cog-6-tooth'
  | 'currency-dollar'
  | 'document'
  | 'document-duplicate'
  | 'ellipsis-horizontal'
  | 'ellipsis-horizontal-circle'
  | 'ellipsis-vertical'
  | 'envelope'
  | 'envelope-open'
  | 'exclamation-circle'
  | 'exclamation-triangle'
  | 'eye'
  | 'fire'
  | 'flag'
  | 'folder'
  | 'funnel'
  | 'hand-thumb-up'
  | 'inbox'
  | 'information-circle'
  | 'key'
  | 'life-buoy'
  | 'link'
  | 'lock-closed'
  | 'magnifying-glass'
  | 'megaphone'
  | 'minus'
  | 'minus-circle'
  | 'no-symbol'
  | 'paper-clip'
  | 'pencil-square'
  | 'photo'
  | 'plus'
  | 'presentation-chart-bar'
  | 'queue-list'
  | 'rectangle-stack'
  | 'shield-check'
  | 'sparkles'
  | 'square-3-stack-3d'
  | 'squares-2x2'
  | 'squares-plus'
  | 'star'
  | 'table-cells'
  | 'tag'
  | 'trash'
  | 'trophy'
  | 'user'
  | 'user-circle'
  | 'user-group'
  | 'user-plus'
  | 'users'
  | 'x-circle'
  | 'x-mark';

export declare const ICON_NAMES: IconName[];

export interface IconProps extends React.SVGProps<SVGSVGElement> {
  /** Glyph name — see ICON_NAMES. */
  name: IconName;
  /** Pixel box; 24 for nav, 20 inline, 16 in dense cells. Default 20. */
  size?: number;
  /** Stroke weight. Default 1.5. */
  strokeWidth?: number;
}

/** Heroicons v2 outline glyph. Inherits currentColor. */
export declare function Icon(props: IconProps): JSX.Element | null;
